# -*- coding: utf-8 -*-
"""GoogleDrive-With-Cloab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189BljnIG9k0y940ZVKvJkkx4hO2x8d45
"""

from google.colab import drive

drive.mount('/content/drive')

import os

folder_path = '/content/drive/MyDrive/CASHSKOOL/Amazon'

file_names = os.listdir(folder_path)

for file_name in file_names:
    print(file_name)

video_extensions = ('.mp4', '.mov', '.avi')
for file_name in file_names:
    if file_name.endswith(video_extensions):
        print(file_name)